# Generated by Django 3.0.5 on 2020-08-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='SessionID',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
