# Generated by Django 3.0.5 on 2020-08-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='sessions',
            field=models.TextField(blank=True),
        ),
    ]
